In [42]:
import numpy as np
import pandas as pd 

In [43]:
vet = np.array([1,2,3,95,8,45,67,25,35,29,38,65,45,92,9])
vet

array([ 1,  2,  3, 95,  8, 45, 67, 25, 35, 29, 38, 65, 45, 92,  9])

In [44]:
type(vet)

numpy.ndarray

In [45]:
vet2 = np.array([1,2,3,4,5])
vet2.cumsum()

array([ 1,  3,  6, 10, 15])

In [46]:
print(vet[4])

8


In [47]:
vet[0] = -1
vet

array([-1,  2,  3, 95,  8, 45, 67, 25, 35, 29, 38, 65, 45, 92,  9])

In [48]:
vet = np.append(vet,202)
vet

array([ -1,   2,   3,  95,   8,  45,  67,  25,  35,  29,  38,  65,  45,
        92,   9, 202])

In [49]:
vet = vet[:-1]
vet

array([-1,  2,  3, 95,  8, 45, 67, 25, 35, 29, 38, 65, 45, 92,  9])

In [50]:
vet = np.delete(vet,-3)
vet

array([-1,  2,  3, 95,  8, 45, 67, 25, 35, 29, 38, 65, 92,  9])

In [51]:
vet.shape

(14,)

In [52]:
vetor = np.array([[0, -5],[11, 300]])
vetor

array([[  0,  -5],
       [ 11, 300]])

In [53]:
vetor.shape

(2, 2)

In [54]:
vetor3x2 = np.array([[1,2],[3,4],[5,6]])
vetor3x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
vetor2x3 =np.array([[1,2,3],[4,5,6]])
vetor2x3

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
vetor2x3.shape

(2, 3)

In [57]:
y = np.arange(2,200,5)
y

array([  2,   7,  12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,
        67,  72,  77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127,
       132, 137, 142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192,
       197])

In [58]:
unicos_vet = np.unique(vet)
unicos_vet

array([-1,  2,  3,  8,  9, 25, 29, 35, 38, 45, 65, 67, 92, 95])

In [60]:
idadesIA2 = np.array([44,45,23,23,28,19,20,19,17,51,29,28,31,32])
mediaIA2 = round(idadesIA2.mean(),3)
mediaIA2

np.float64(29.214)

In [62]:
j = np.unique(idadesIA2)
j

array([17, 19, 20, 23, 28, 29, 31, 32, 44, 45, 51])